import type { Metadata } from "next";
import { Geist, Geist_Mono, Bungee, Montserrat } from "next/font/google";
import "./globals.css";

// import components
import Header from "@/components/Header";

// import shadcn
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const bungee = Bungee({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bungee",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-montserrat",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MINI GARAGE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${bungee.variable} ${geistSans.variable} ${geistMono.variable} ${montserrat.variable}
          antialiased
          `}
      >
        <Header />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
